### ISSUE TITLE
Previsualización de github...

### ISSUE THREAD

**Issue by csoroz** [jaalonso/Lecturas_GLC#1]
El contenido del README.org lo muestra correctamente en github, pero la previsualización se corta por:
![Untitled](https://user-images.githubusercontent.com/3624828/72354492-29ce8600-36e6-11ea-9bc0-12ca38d9fc8f.png)

**Comment by csoroz** [comment]
Ahora se corta por otro punto. Parece ser una limitación de tamaño de github.

**Comment by jaalonso** [comment]
Efectivamente, hay un problema con el tamaño. Para evitarlo he separado las lecturas por año y he dejado en el README.org la del año actual y enlaces a los anteriores.
